CREATE TABLE ALUNO (
    Cpf CHAR(11) NOT NULL,
    Nome VARCHAR(20) NOT NULL,
    Sobrenome VARCHAR(50) NOT NULL,
    Sexo CHAR(1) CHECK(Sexo IN ('M', 'F')),
    DataNasc DATE,
    PRIMARY KEY(Cpf)
);

CREATE TABLE AREA (
    Sigla VARCHAR(10) NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    SuperArea VARCHAR(10),
    PRIMARY KEY(Sigla),
    FOREIGN KEY(SuperArea) REFERENCES AREA(Sigla)
);

CREATE TABLE CURSO (
    Sigla VARCHAR(10) NOT NULL,
    Nome VARCHAR(50) NOT NULL UNIQUE,
    Horas INT NOT NULL CHECK(Horas > 0),
    Custo DECIMAL(10, 2) NOT NULL CHECK(Custo >= 0),
    Area VARCHAR(10),
    PRIMARY KEY(Sigla),
    FOREIGN KEY(Area) REFERENCES AREA(Sigla)
);

CREATE TABLE MODULO (
    Sigla VARCHAR(10) NOT NULL,
    Nome VARCHAR(50) NOT NULL UNIQUE,
    Curso VARCHAR(10) NOT NULL,
    PRIMARY KEY(Sigla),
    FOREIGN KEY(Curso) REFERENCES CURSO(Sigla)
);

CREATE TABLE PROFESSOR (
    Curso VARCHAR(10) NOT NULL,
    Cpf CHAR(11) NOT NULL,
    Nome VARCHAR(50) NOT NULL,
    PRIMARY KEY(Curso, Cpf),
    FOREIGN KEY(Curso) REFERENCES CURSO(Sigla)
);

CREATE TABLE MATRICULA (
    Curso VARCHAR(10) NOT NULL,
    Aluno CHAR(11) NOT NULL,
    DataMat DATE DEFAULT CURRENT_DATE,
    Pago CHAR(1) DEFAULT 'N' CHECK(Pago IN ('S', 'N')),
    PRIMARY KEY(Curso, Aluno),
    FOREIGN KEY(Curso) REFERENCES CURSO(Sigla),
    FOREIGN KEY(Aluno) REFERENCES ALUNO(Cpf)
);

CREATE TABLE TOPICO (
    Modulo VARCHAR(10) NOT NULL,
    Sigla VARCHAR(10) NOT NULL,
    Nome VARCHAR(20) NOT NULL UNIQUE,
    Horas INT CHECK(Horas > 0),
    PRIMARY KEY(Modulo, Sigla),
    FOREIGN KEY(Modulo) REFERENCES MODULO(Sigla)
);